### PR TITLE
Added section for Netlify _redirects

### PR DESCRIPTION
**Pull request by candidexmedia**

### CODE REVIEW

**Review by snarfed — COMMENTED** [review]
Thank you for the contribution!

I should have asked this on the first Netlify PR, but better late than never: why does host-meta have :splat but webfinger doesn't?

**Comment by candidexmedia** [comment]
Looks like it's a Netlify thing: https://docs.netlify.com/routing/redirects/redirect-options/#splats

**Comment by candidexmedia** [comment]
Hmmm.... Good question. Not sure.

**Comment by snarfed** [comment]
Thanks @candidexmedia! I'll look more too

**Pull request closed without merging**
